# Generated by Django 4.2.1 on 2023-06-07 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='carrier',
            field=models.ForeignKey(default=1, limit_choices_to={'role__role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
