# Generated by Django 4.2.1 on 2023-06-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_subject_code_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('upisan', 'Upisan'), ('neupisan', 'Neupisan'), ('polozen', 'Položen')], max_length=255),
        ),
    ]
