# Generated by Django 4.2.1 on 2023-06-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('upisan', 'Upisan'), ('potpis izgubljen', 'Potpis izgubljen'), ('polozen', 'Položen')], max_length=255),
        ),
    ]
